# Generated by Django 3.2.16 on 2023-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230217_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_countries',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
